name: Checkout
on: [push]

jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -a
      - name: echo $GITHUB_ACTOR
        run: | 
            echo "GITHUB_ACTOR: "$GITHUB_ACTOR
            echo "GITHUB_REPOSITORY: "$GITHUB_REPOSITORY
            echo "secrets.GITHUB_TOKEN : "${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List Files After
        run: ls -a