name: External Events
# ca permet de declencher ce workflow a distance via api
on:
  repository_dispatch:
    types: [build]
jobs:
  echo-a-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload.env }}