name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World soufiane"
      - name: Multiline Command
        run: |
          node -v
          npm -v
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View SW Version
        run: sw_vers
  dependant-job:
    runs-on: windows-latest
    needs: run-shell-commands # need, ce job se lance quand le job run-shell--commands fini
    steps:
      - name: echo a string
        run: Write-Output "Windows String"